# Generated by Django 2.2.4 on 2020-06-29 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_statics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTPDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('otp_type', models.CharField(choices=[('hotp', 'HOTP'), ('totp', 'TOTP'), ('webauthn', 'WebAuthn')], max_length=24)),
                ('destination_type', models.CharField(choices=[('sms', 'SMS'), ('call', 'Call'), ('email', 'Email'), ('device', 'Generator device')], max_length=24)),
                ('destination_value', models.CharField(blank=True, max_length=80)),
                ('data', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('counter', models.BigIntegerField(default=0, help_text='The next counter value to expect.')),
                ('last_use_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
